import turtle
import math
turtle.bgcolor("black")
turtle.pencolor('red')

def drawRectangle(t, width, height, color):
  t.fillcolor(color)
  t.begin_fill()
  t.forward(width)
  t.left(90)
  t.forward(height)
  t.left(90)
  t.forward(width)
  t.left(90)
  t.forward(height)
  t.left(90)
  t.end_fill()
  
def drawTriangle(t, length, color):
  t.fillcolor(color)
  t.begin_fill()
  t.forward(length)
  t.left(135)
  t.forward(length / math.sqrt(2))
  t.left(90)
  t.forward(length / math.sqrt(2))
  t.left(135)
  t.end_fill()

def drawParallelogram(t, width, height, color):
  t.fillcolor(color)
  t.begin_fill()
  t.left(30)
  t.forward(width)
  t.left(60)
  t.forward(height)
  t.left(120)
  t.forward(width)
  t.left(60)
  t.forward(height)
  t.left(90)
  t.end_fill()
  
def drawFourRays(t, length, radius):
  for i in range(4):
    t.penup()
    t.forward(radius)
    t.pendown()
    t.forward(length)
    t.penup()
    t.backward(length + radius)
    t.left(90)

turtle.penup() 
turtle.goto(-150, -120)
turtle.pendown()
drawRectangle(turtle, 100, 110, "blue")
turtle.penup()
turtle.goto(-120, -120)
turtle.pendown()
drawRectangle(turtle, 40, 60, "black")

turtle.penup()
turtle.goto(-150, -10)
turtle.pendown()
drawTriangle(turtle, 100, "red")

turtle.penup()
turtle.goto(-50, -120)
turtle.pendown()
drawParallelogram(turtle, 60, 110, "blue")

turtle.penup()
turtle.goto(-30, -60)
turtle.pendown()
drawParallelogram(turtle, 20, 30, "white")

turtle.penup()
turtle.goto(-50, -10)
turtle.pendown()
turtle.fillcolor("pink")
turtle.begin_fill()
turtle.left(30)
turtle.forward(60)
turtle.left(105)
turtle.forward(100 / math.sqrt(2))
turtle.left(75)
turtle.forward(60)
turtle.left(105)
turtle.forward(100 / math.sqrt(2))
turtle.left(45)
turtle.end_fill()
turtle.penup()
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.left(90)

turtle.pendown()
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.circle(30)
turtle.right(90)
turtle.forward(40)
turtle.right(120)
turtle.forward(50)
turtle.left(180)
turtle.forward(50)
turtle.left(60)
turtle.forward(50)
turtle.left(180)
turtle.forward(50)
turtle.left(60)
turtle.forward(70)
turtle.right(40)
turtle.forward(50)
turtle.right(180)
turtle.forward(50)
turtle.right(100)
turtle.forward(50)
turtle.penup()
turtle.forward(34234)
